[color]
primaryColors = [
    "#7FB5CD"    
] # primary colors hex codes
maxDiff = 5 # max deviation a color may have for it to be accepted

[drilling]
minHoleSize = 0.5 # minimum hole diameter in mm,
holeMargin = 0.5
strategy = "stacked" # or grouped

[image]
grayscale = false  # if image should be grayscale
size = [5, 5] # resize image to size, in pixel 

[workpiece]
dimensions = [
    250,
    250,
] # workpiece dimensions in mm, image will be stretched over the size

[output]
format = "svg" # output format, can be "dxf" or "svg"